name:                json-final
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/json-final#readme
license:             MIT
author:              Evgeny Poberezkin
copyright:           2020 Evgeny Poberezkin
category:            JSON
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Data.Json

executables:
  json-final:
    source-dirs:      src
    main:             Main.hs
